# Generated by Django 3.0.5 on 2020-04-05 21:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project_gate_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('identifier', models.CharField(max_length=8)),
                ('use_case_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('owner', models.CharField(max_length=50)),
                ('sponsor', models.CharField(max_length=50)),
                ('directorate', models.CharField(max_length=50)),
                ('timeline', models.CharField(max_length=2)),
                ('cost', models.CharField(max_length=20)),
                ('use_case_benefits', models.CharField(max_length=100)),
                ('stake_benefits', models.CharField(max_length=100)),
            ],
        ),
    ]
