# Generated by Django 3.0.5 on 2020-04-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_gate_1',
            name='cost',
            field=models.CharField(choices=[('0 - 50,000', '£0 - £50,000'), ('50,000 - 100,000', '£50,000 - £100,000'), ('100,000 - 500,000', '£100,000 - £500,000'), ('500,000 - 1000,000', '£500,000 - £1000,000'), ('1000,000 - 2000,000', '£1000,000 - £2000,000'), ('2000,000 - 5000,000', '£2000,000 - £5000,000'), ('5000,000 - 10,000,000', '£5000,0000 - £10,000,000'), ('10,000,000 - 20,000,000', '£10,000,000 - £20,000,000'), ('> 20,0000,000', 'More than £20,000,000')], max_length=25),
        ),
        migrations.AlterField(
            model_name='project_gate_1',
            name='directorate',
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='project_gate_1',
            name='stake_benefits',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project_gate_1',
            name='timeline',
            field=models.CharField(choices=[('< 1', 'Less than one month'), ('1 - 6', '1 to 6 months'), ('6 - 12', '6 months to 1 year'), ('12 - 24', '1 to 2 years'), ('24 - 60', '1 to 5 years'), ('> 60', 'More than 5 years')], max_length=10),
        ),
        migrations.AlterField(
            model_name='project_gate_1',
            name='use_case_benefits',
            field=models.TextField(),
        ),
    ]
