# Generated by Django 3.0.5 on 2020-04-08 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200408_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_gate_1',
            name='strat_customer',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project_gate_1',
            name='strat_deliver',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project_gate_1',
            name='strat_safety',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
