# Generated by Django 3.0.5 on 2020-04-10 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200408_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_gate_1',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
