# Generated by Django 3.0.5 on 2020-04-11 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_project_gate_1_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_gate_1',
            name='comments',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
